use_frameworks!

platform :ios, '9.0'

target 'BreakingNews_Example' do
  pod 'BreakingNews', :path => '../'

  target 'BreakingNews_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
